"""empty message

Revision ID: e9c7b5a17de5
Revises: 
Create Date: 2021-10-27 23:12:24.185089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c7b5a17de5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobseekers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('bio', sa.String(length=1024), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.String(length=7), nullable=False),
    sa.Column('end_date', sa.String(length=7), nullable=False),
    sa.Column('currently', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['jobseekers.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('vacancy_number', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('working_hours', sa.Integer(), nullable=True),
    sa.Column('minimum_experience', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['companies.company'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['jobseekers.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.String(length=7), nullable=False),
    sa.Column('end_date', sa.String(length=7), nullable=False),
    sa.Column('currently', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['jobseekers.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experiences')
    op.drop_table('skills')
    op.drop_table('job_offer')
    op.drop_table('educations')
    op.drop_table('jobseekers')
    op.drop_table('companies')
    # ### end Alembic commands ###
