from resources.JobSeekers import JobSeekers
from resources.Companies import Companies
from resources.Login import Login
from resources.Register import Register
from resources.Educations import Educations
from resources.WorkExperiences import WorkExperiences
from resources.CompanyList import CompanyList
from resources.JobOffers import JobOffers
from resources.CompanyJobOffers import CompanyJobOffers
from resources.JobOfferList import JobOfferList
from resources.DeleteEducation import DeleteEducation
from resources.DeleteWorkExperience import DeleteWorkExperience
from resources.Applications import Applications
from resources.DeleteApplication import DeleteApplication
